# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 521599dbe91a060d3eb100a0f6848d4b3a773257b24bd76027154a7d90961e264e0c60a8504e31d901d9e4517fb9bfd2401694bf31b8f67b2579cd0c3555cce6

test:
  secret_key_base: 5350745a59cb2ef8f23a8c58a79f1a24c5f90927973e25aedb98bbe1c79079f5ae4d354c56746f75f12b1252814d435f85620f604ce69e374522f0b8d5f7bccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
